### ISSUE TITLE
Can db2mt tool migrate data from DB2 on cloud(non-Azure cloud) to DB2 on Azure

### ISSUE THREAD

**Issue by vmnaidu2018** [IBM/db2-db2mt#3]
Please clarify whether we can use db2mt tool to migrate data from DB2 on cloud(non-Azure cloud) to DB2 on Azure cloud.

**Comment by eunicechung** [comment]
Hello,

The current intended use case is mainly to migrate to RDS for Db2.  As a result, some of the steps are specific to AWS.
The tool underneath uses db2look and db2 export/load, which are common for a lot of db2 migrations.  So while you probably can't use it to migrate from Db2 on Cloud to Db2 on Azure Cloud directly, you can try to generate sample migration scripts from the tool and use them as base to create your own scripts.

Thanks.
